apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oz-test-pod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        context: microservices
        service: oz-test
    spec:
      containers:
        - name: oz-test
          image: gcr.io/ornate-axiom-187403/oz-test-sq1:0.0.5
          imagePullPolicy: Always
          env:
            - name: GIT_HASH
              value: d28f65f1ce702fb60d3dc06a17dac3d7405565b2
            - name: SCRIPT_NAME
              value: sq1
          # ports:
          #   - containerPort: 14000
          resources:
            requests:
              cpu: 31
          volumeMounts:
            - mountPath: /oz-test-logs
              name: logs
      volumes:
        - name: logs
          emptyDir: {}
        
