apiVersion: batch/v1
kind: Job
metadata:
  name: oz-test
spec:
  template:
    spec:
      containers:
      - name: pi
        image: gcr.io/ornate-axiom-187403/oz-test-sq1:0.0.4
        command: ["/bin/bash", "-c", "experiments/scripts/run-test-${SCRIPT_NAME}.sh"]
        env:
          - name: GIT_HASH
            value: PROD
          - name: SCRIPT_NAME
            value: sq1
        resources:
            requests:
              cpu: 31
      restartPolicy: Never
  backoffLimit: 1